import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import Main from '../components/Main';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Background from '../components/Background';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <section
          className={`text-white px-20 h-screen w-[1fr] flex flex-row items-center flex-wrap justify-center ${inter.className}`}
        >
          <Header />
          <Header />
          <Header />
          <Header />
          <Header />
          <Header />
          <Header />
          <Header />
          <Background />
        </section>
        {/* <Main /> */}
        {/* <Footer /> */}
      </main>
    </>
  );
}
